export enum RegistrationSubRouteType {
    email = 'email',
    role = 'role',
    address = 'address',
    children = 'children',
    fosterRole = 'foster-role',
    genderBirthday = 'gender-birthday',
    availabilityType = 'availability-type',
    availabilitySchedule = 'availability-schedule',
    chores = 'chores',
    willingToPay = 'willing-to-pay',
    about = 'about',
    photo = 'photo',
    experienceYears = 'experience-years',
    experienceAgeGroups = 'experience-age-groups',
    references = 'references',
    nativeLanguage = 'native-language',
    otherLanguages = 'languages',
    childrenAmount = 'children-amount',
    additionalOptions = 'additional-options',
    hourlyRate = 'hourly-rate',
    fosterTraits = 'foster-traits',
}
