import { UserResponse } from './user-response';

export class UserResponseAttributes {
    static gemSitlyUserSummarized: (keyof UserResponse)[] = [
        'id',
        'email',
        'firstName',
        'lastName',
        'gender',
        'role',
        'placeName',
        'streetName',
        'created',
        'lastLogin',
        'isPremium',
        'completed',
        'disabled',
        'deleted',
        'active',
        'subscription',
        'inappropriate',
        'suspected',
        'notes',
        'warnings',
        'photos',
        'quarantinedAt',
        'invisible',
    ];

    static gemSitlyUser: (keyof UserResponse)[] = [
        ...UserResponseAttributes.gemSitlyUserSummarized,
        'about',
        'publicProfileUrl',
        'age',
        'homepage',
        'hasPublicProfile',
        'searchPreferences',
        'fosterProperties',
        'photos',
        'recommendations',
        'localeCode',
        'postalCode',
        'houseNumber',
        'birthdate',
        'receiveMatchMail',
        'subscriptionCancelled',
        'children',
        'payments',
        'gracePeriod',
        'premiumExpiryDate',
        'premiumExtensionUsed',
        'discountPercentage',
        'subscriptionPsp',
        'paymentMethod',
        'subscriptionCancellationDate',
    ];

    static public: (keyof UserResponse)[] = [
        'id',
        'role',
        'firstName',
        'about',
        'created',
        'updated',
        'lastLogin',
        'latitude',
        'longitude',
        'placeName',
        'place',
        'children',
        'gender',
        'age',
        'education',
        'homepage',
        'hasPublicProfile',
        'searchPreferences',
        'fosterProperties',
        'references',
        'recommendations',
        'photos',
        'similar',
        'averageRecommendationScore',
        'availabilityUpdated',
        'availableForChat',
        'lastSearchActivity',
        'isPremium',
        'localeCode',
        'avatar',
    ];

    static private: (keyof UserResponse)[] = [
        ...UserResponseAttributes.public,
        'email',
        'lastName',
        'streetName',
        'postalCode',
        'province',
        'houseNumber',
        'completed',
        'disabled',
        'invisible',
        'premiumExpiryDate',
        'subscriptionPsp',
        'paymentMethod',
        'birthdate',
        'receiveNewMessagesMail',
        'receiveMatchMail',
        'shareProfileWithPartners',
        'subscriptionCancelled',
        'accessToken',
        'facebookId',
        'jobPostingDisabledTill',
        'subscription',
        'disabledSafetyMessages',
        // FIXME: - how do we restore this ?
        // 'avatarWarnings',
        'discountPercentage',
        'discountOfferedDate',
        'emailBounced',
        'aTestVersion',
    ];
}
